// frontend/src/contents/Login.jsx
import React, {useState} from 'react';

const axios = require("axios").default;

const Login = () => {
    let [loginState, setLoginState] = useState("")

    const handleLogin = (event) => {
        event.preventDefault();
        const formdata = new FormData(event.target);
        setLoginState("loading")
        axios.post(process.env.REACT_APP_APIURL + "/auth/login", {
            username: formdata.get("username"),
            password: formdata.get("password")
        }).then(res => {
            setLoginState("")
            localStorage.setItem("username", res.data.Username)
            localStorage.setItem("token", res.data.Token)
            //navigate("/boats")
        }).catch(err => {
            if (err.response)
                setLoginState(err.response.data)
            else
                setLoginState("Server connection failed")
            setTimeout(() => setLoginState(""), 2500)
        })
    }

    return (
        <div className="flex min-h-screen bg-gray-100">
            <div className="my-auto mx-auto pb-10">
                <div className="flex select-none cursor-default">
                    {loginState !== "" ?
                        <div
                            className={"ml-3 mr-4 my-3 rounded-full h-4 w-4 " + (loginState === "loading" ? "bg-amber-500" : "bg-red-500")}
                        >
                            <div className={"h-4 w-4 animate-ping rounded-full " + (loginState === "loading" ? "bg-amber-400" : "bg-red-400")}/>
                        </div>

                        :
                        <p className="my-auto mr-1 text-4xl">🌊</p>
                    }
                    <div>
                        <h1 className="font-bold text-3xl">Waterway</h1>
                        <p className="uppercase font-semibold text-sm tracking-wider text-gray-500 ml-1 -mt-2">CosmicSail</p>
                    </div>
                </div>

                <form className="mt-2" onSubmit={handleLogin}>
                    <div className="space-y-1">
                        <div>
                            <input name="username" required
                                   className="rounded px-1 shadow-sm hover:shadow w-full focus:outline-none focus:ring ring-indigo-400 transition duration-150"
                                   type="name"/>
                        </div>
                        <div>
                            <input name="password" required
                                   className="rounded px-1 shadow-sm hover:shadow w-full focus:outline-none focus:ring ring-indigo-400 transition duration-150"
                                   type="password"/>
                        </div>
                    </div>
                    <button type="submit"
                            className="rounded px-1 mt-2 bg-amber-500 w-full text-white focus:outline-none hover:ring focus:ring ring-amber-400 transition-all duration-150">Login
                    </button>
                </form>
            </div>
        </div>
    );
};

export default Login;

// frontend/src/views/Login.svelte
<script>
    import {navigate} from "svelte-routing";
    import axios from "axios";
    import Button from "../components/Button.svelte";

    let loginError = ""
    let loading = false

    function handleLogin(event) {
        event.preventDefault();
        const formdata = new FormData(event.target);
        loading = true
        axios.post(process.env.APIURL + "/auth/login", {
            username: formdata.get("username"),
            password: formdata.get("password")
        }).then(res => {
            loading = false
            console.log(res)
            localStorage.setItem("username", res.data.Username)
            localStorage.setItem("token", res.data.Token)
            navigate("/boats")
        }).catch(err => {
            loading = false
            console.log(err.response)
            if (err.response)
                loginError = err.response.data
            else
                loginError = "Server connection failed"
        })
    }
</script>

<main class="mt-12 pb-10 mx-10 sm:flex sm:justify-center sm:items-center h-full md:pt-48">
    <div class="sm:mr-10 md:mr-24 my-auto">
        <ion-icon style="font-size: 40px;" class="-mb-2 dark:text-white" name="lock-open"></ion-icon>
        <h1 class="text-5xl font-dosis font-bold dark:text-white">Login</h1>
        <p class="text-gray-700 dark:text-gray-500">
            In order to use <span class="font-semibold">CosmicSail</span>,
            you have to log in.
        </p>
        {#if loginError !== ""}
            <div class="my-2 p-2 mr-auto rounded text-white bg-red-500">
                {loginError}
            </div>
        {/if}
    </div>
    <form on:submit={handleLogin} class="mt-5 sm:my-auto flex-col">
        <p class="mb-2 uppercase text-sm font-semibold tracking-wide text-gray-500 dark:text-gray-300">Credentials</p>
        <div class="mb-2">
            <label>
                <input placeholder="username"
                       type="text"
                       name="username"
                       required
                       class="placeholder-gray-500 transition duration-200 dark:bg-gray-900 dark:text-gray-200 p-2 w-full rounded shadow focus:outline-none focus:shadow-md"
                />
            </label>
        </div>
        <div>
            <label>
                <input placeholder="password"
                       type="password"
                       name="password"
                       required
                       class="placeholder-gray-500 transition duration-200 dark:bg-gray-900 dark:text-gray-200 p-2 w-full rounded shadow focus:outline-none focus:shadow-md"
                />
            </label>
        </div>
        <Button isPrimary={true} className="my-3 px-8" text="{loading ? 'Loading' : 'Login'}" type="submit"/>
    </form>
</main>
